version: '3.8'

services:
  server:
    build:
      context: ./dockerfiles
      dockerfile: nginx.dockerfile
    ports:
      - '8000:80'
    volumes:
      - ./src:/var/www/html
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
  mysql:
    image: mysql:latest
    env_file:
      - ./env/mysql.env
    volumes:
      - ./data/db:/var/lib/mysql
    ports:
      - '3307:3306'
    expose:
      - 3307
  npm:
    image: node:latest
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes:
      - ./src:/var/www/html
